# Univariate Logistic Regression

```{r, results='hide', include = FALSE}
univariate_lr <- function(gender, disease) {
  options(scipen=999)
  print(disease)
  df <- data.frame(Variable_Name=character(), Odds_Ratio=numeric(), Conf_25=numeric(), Conf_75=numeric(), P_Value=numeric())
  f_path = paste(disease,'/split/',gender,sep='')
  files <- list.files(path=f_path, pattern="*.csv", full.names=TRUE, recursive=FALSE)

  for (f in files) {
    data <- read.csv(file =f)
    names(data)[ncol(data)] <- 'y'
    res = glm(y ~ .,data=data,family=binomial())
    trm <- attr(res$terms, "term.labels")
    for (i in (seq(2,dim(data)[2],by=1))) {
      res_vec <- tryCatch(c(trm[i-1], exp(summary(res)$coef[i,][1]), exp(confint(res)[i,]), summary(res)$coef[i,][4]), error=function(e) c(NA,NA,NA,NA,NA))
      df[nrow(df) + 1,] = res_vec
    }
    
  }
  adjusted <- p.adjust(df[, c('P_Value')], method="BH")
  df$Adjusted_P = adjusted
  
  df <- df[order(df$P_Value),]
  df
}
```

```{r, results='hide', include = FALSE}
top_univariate_lr <- function(disease, n=10) {
  options(scipen=999)
  if (n == 10) {
    filename = '10feature_dataset.csv'
  } else {
    filename = '20feature_dataset.csv'
  }
  f_path = paste(disease,'/top/',filename,sep='')
  data <- read.csv(f_path)
  
  df <- data.frame(Variable_Name=character(), Odds_Ratio=numeric(), Conf_25=numeric(), Conf_75=numeric(), P_Value=numeric())
  names(data)[ncol(data)] <- 'y'
  for (i in 1:dim(data)[2]) {
    res = glm(y ~ .,data=subset(data, select=c(i, ncol(data))),family=binomial())
    a <- c( colnames(data)[i], exp(summary(res)$coef[2,][1]), exp(confint(res)[2,]), summary(res)$coef[2,][4])
    df[nrow(df) + 1,] = a
  }
  adjusted <- p.adjust(df[, c('P_Value')], method="BH")
  df$Adjusted_P = adjusted
  df <- df[order(df$P_Value),]
  
  df
}
```


```{r, include = FALSE}
create_table <- function(dataframe, label) {
  kableExtra::kable_styling(knitr::kable(dataframe[dataframe$P_Value <= 0.05,], booktabs = TRUE, 
      caption = label), font_size = 10)
}
```

## Without AGE & SOCIOSTATUS

### BDI

#### One-Way


```{r, results='hide', include = FALSE}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/statistical-analysis/analysis-nocli/")
BDI1way_gendered <- univariate_lr('gendered','BDI1way')
BDI1way_male <- univariate_lr('male','BDI1way')
BDI1way_female <- univariate_lr('female','BDI1way')
```

```{r, echo=FALSE}
create_table(BDI1way_gendered, label='Combined Gender')
```

```{r, echo=FALSE}
create_table(BDI1way_male, label='Males only.')
```

```{r, echo=FALSE}
create_table(BDI1way_female, label='Females only.')
```


#### Two-Way

```{r, results='hide', include = FALSE}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/statistical-analysis/analysis-nocli/")
BDI2way_gendered <- univariate_lr('gendered','BDI2way')
BDI2way_male <- univariate_lr('male','BDI2way')
BDI2way_female <- univariate_lr('female','BDI2way')
```


```{r, echo=FALSE}
create_table(BDI2way_gendered, label='Combined Genders')
```

```{r, echo=FALSE}
create_table(BDI2way_male, label='Males only.')
```

```{r, echo=FALSE}
create_table(BDI2way_female, label='Females only.')
```

### STAI

#### One-Way

```{r, results='hide', include = FALSE}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/statistical-analysis/analysis-nocli/")
STAI1way_gendered <- univariate_lr('gendered','STAI1way')
STAI1way_male <- univariate_lr('male','STAI1way')
STAI1way_female <- univariate_lr('female','STAI1way')
```

```{r, echo=FALSE}
create_table(STAI1way_gendered,label='Combined Genders')
```


```{r, echo=FALSE}
create_table(STAI1way_male,label='Males Only.')
```


```{r, echo=FALSE}
create_table(STAI1way_female,label='Females Only.')
```

#### Two-Way

```{r, results='hide', include = FALSE}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/statistical-analysis/analysis-nocli/")
STAI2way_gendered <- univariate_lr('gendered','STAI2way')
STAI2way_male <- univariate_lr('male','STAI2way')
STAI2way_female <- univariate_lr('female','STAI2way')
```


```{r, echo=FALSE}
create_table(STAI2way_gendered,label='Combined Genders')
```

```{r, echo=FALSE}
create_table(STAI2way_male,label='Males Only')
```

```{r, echo=FALSE}
create_table(STAI2way_female,label='Females Only.')
```

