# Multivariate Logistic Regression

```{r, results='hide', include = FALSE}
multivariate_lr_old <- function(gender, disease) {
  
  f_path <- paste(disease,'/combined/',gender,'/combined.csv',sep='')
  data2 <- read.csv(file =f_path)
  multi = glm(BDI ~ ., data=data2, family=binomial())
  placeholder = data.frame(multi_log_odds=numeric(), multi_conf25=numeric(), multi_conf75=numeric(), P_Value=numeric(), name=character())

  for (i in seq(2, (length(summary(multi)$coef)/4), by=1)){
    trm <- attr(multi$terms, "term.labels")
    if (is.na(multi$coefficients[i])) {
      b <- c(NA, NA, NA, NA, trm[i-1])
      placeholder[nrow(placeholder) + 1,] = b
    } else {
      a <- tryCatch(confint(multi, trm[i-1]), error=function(e) c(NA,NA))
      b <- c(exp(summary(multi)$coef[i,][1]), a, summary(multi)$coef[i,][4], trm[i-1])
      #b <- c(exp(multi$coefficients[i]), a, coef(summary(multi))[i,][4], trm[i-1])
      placeholder[nrow(placeholder) + 1,] = b
    }
  }

  adjusted2 <- p.adjust(placeholder[, c('P_Value')], method="BH")
  placeholder$multi_adjusted_p = adjusted2
  
  placeholder <- placeholder[order(placeholder$P_Value),]
  placeholder
}
```

```{r, results='hide', include = FALSE}
multivariate_lr <- function(gender, disease) {
  library(tidyverse)
  options(scipen=999)
  df <- tibble(Variable_Name=character(), Odds_Ratio=numeric(), Conf_25=numeric(), Conf_75=numeric(), P_Value=numeric())
  
  f_path <- paste(disease,'/combined/',gender,'/combined.csv',sep='')
  data2 <- read.csv(file =f_path)
  if (grepl('BDI',disease,fixed=TRUE)) {
    y <- as.formula(BDI ~ .)
  } else if (grepl('STAI',disease,fixed=TRUE)) {
    y <- as.formula(STAI ~ .)
  } else {
    y <- as.formula(MEQ ~ .)
  }
  
  multi = glm(y, data=data2, family=binomial())
  trm <- attr(multi$terms, "term.labels")

  
  for (i in seq(2, dim(data2)[2], by=1)){

    if (is.na(multi$coefficients[i])) {
      df <- df %>% add_row(Variable_Name = trm[i-1], 
                           Odds_Ratio = NA, 
                           Conf_25 = NA, 
                           Conf_75 = NA,
                           P_Value = NA)
    } else {
      a <- tryCatch(exp(confint(multi, trm[i-1])), error=function(e) c(NA,NA))
      b <- tryCatch(exp(summary(multi)$coef[i,][1]), error=function(e) c(NA))
      c <- tryCatch(summary(multi)$coef[i,][4], error=function(e) c(NA))
      df <- df %>% add_row(Variable_Name = trm[i-1], 
                           Odds_Ratio = b, 
                           Conf_25 = a[1],  
                           Conf_75 = a[2],
                           P_Value = c)
    }
  }

  adjusted2 <- p.adjust(as.numeric(unlist(df %>% select(P_Value))), method="BH")
  df <- df %>% add_column(Adjusted_P = adjusted2)
  
  df <- df %>% arrange(P_Value)
  df
}
```

```{r, echo=TRUE}
create_table <- function(dataframe, label) {
  kableExtra::kable_styling(knitr::kable(dataframe %>% filter(P_Value <=0.05), booktabs = TRUE, 
      caption = label), font_size = 10)
}
```


## Without AGE & SOCIOSTATUS

### BDI

```{r, results='hide', include = FALSE}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/statistical-analysis/analysis-nocli/")
BDI1way_gendered <- multivariate_lr('gendered','BDI1way')
BDI1way_male <- multivariate_lr('male','BDI1way')
BDI1way_female <- multivariate_lr('female','BDI1way')
```

#### One-Way

```{r, echo=FALSE}
create_table(BDI1way_gendered, label='Combined Gender')
```

```{r, echo=FALSE}
create_table(BDI1way_male, label='Males only.')
```

```{r, echo=FALSE}
create_table(BDI1way_female, label='Females only.')
```

#### Two-Way

```{r, results='hide', include = FALSE}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/statistical-analysis/analysis-nocli/")
BDI2way_gendered <- multivariate_lr('gendered','BDI2way')
BDI2way_male <- multivariate_lr('male','BDI2way')
BDI2way_female <- multivariate_lr('female','BDI2way')
```


```{r, echo=FALSE}
create_table(BDI2way_gendered, label='Combined Genders')
```

```{r, echo=FALSE}
create_table(BDI2way_male, label='Males only.')
```

```{r, echo=FALSE}
create_table(BDI2way_female, label='Females only.')
```

### STAI

#### One-Way

```{r, results='hide', include = FALSE}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/statistical-analysis/analysis-nocli/")
STAI1way_gendered <- multivariate_lr('gendered','STAI1way')
STAI1way_male <- multivariate_lr('male','STAI1way')
STAI1way_female <- multivariate_lr('female','STAI1way')
```

```{r, echo=FALSE}
create_table(STAI1way_gendered,label='Combined Genders')
```


```{r, echo=FALSE}
create_table(STAI1way_male,label='Males Only.')
```


```{r, echo=FALSE}
create_table(STAI1way_female,label='Females Only.')
```

#### Two-Way

```{r, results='hide', include = FALSE}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/statistical-analysis/analysis-nocli/")
STAI2way_gendered <- multivariate_lr('gendered','STAI2way')
STAI2way_male <- multivariate_lr('male','STAI2way')
STAI2way_female <- multivariate_lr('female','STAI2way')
```


```{r, echo=FALSE}
create_table(STAI2way_gendered,label='Combined Genders')
```

```{r, echo=FALSE}
create_table(STAI2way_male,label='Males Only')
```

```{r, echo=FALSE}
create_table(STAI2way_female,label='Females Only.')
```

