# ANOVA

#BDI
```{r}
library(car)
library(agricolae)
```

```{r, results='hide', include = FALSE}

setwd("/Users/tazmilur/Research/mood-disorder-prediction/statistical-analysis/analysis-nocli/BDI1way")
aov_data <- read.csv(file ='baseanova.csv')
options(contrasts = c("contr.helmert", "contr.poly"))

gender <- as.factor(aov_data$GENDER)
age <- as.factor(aov_data$AGE)
socio <- as.factor(aov_data$SOCIO)
per2<- as.factor(aov_data$PER2)
per3a <- as.factor(aov_data$PER3A)
per3b <- as.factor(aov_data$PER3B)
per3c <- as.factor(aov_data$PER3C)
clock <- as.factor(aov_data$CLOCK3111)
cry1 <- as.factor(aov_data$CRY1)
cry2 <- as.factor(aov_data$CRY2)
vntr <- as.factor(aov_data$VNTR)

model <- lm(BDI ~ gender * per2, data=aov_data)
Anova(model, type="III")

model <- lm(BDI ~ gender * per3a, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(BDI ~ gender * per3b, data=aov_data)
Anova(model, type="III")

model <- lm(BDI ~ gender * per3c, data=aov_data)
Anova(model, type="III")

model <- lm(BDI ~ gender * clock, data=aov_data)
Anova(model, type="III")

model <- lm(BDI ~ gender * cry1, data=aov_data)
Anova(model, type="III")

model <- lm(BDI ~ gender * cry2, data=aov_data)
Anova(model, type="III")

model <- lm(BDI ~ gender * vntr, data=aov_data)
Anova(model, type="III")

#----------

model <- lm(BDI ~ age * per2, data=aov_data)
Anova(model, type="III")

model <- lm(BDI ~ age * per3a, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(BDI ~ age * per3b, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(BDI ~ age * per3c, data=aov_data)
Anova(model, type="III")

model <- lm(BDI ~ age * clock, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(BDI ~ age * cry1, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(BDI ~ age * cry2, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(BDI ~ age * vntr, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

#-----------
# gender and per2
# age and per2
```

```{r, echo=TRUE}
create_table <- function(dataframe, label) {
  kableExtra::kable_styling(knitr::kable(dataframe, booktabs = TRUE, 
      caption = label), font_size = 10)
}
```

```{r, echo=FALSE}
model <- lm(BDI ~ gender * per2, data=aov_data)
create_table(data.frame(Anova(model, type="III")), 'Gender and PER2')
```

```{r, echo=FALSE}
model <- lm(BDI ~ gender * per2, data=aov_data)
tukey <- HSD.test(model, 'gender')
a <- data.frame(tukey$means)
b <- data.frame(tukey$groups)
tukey_df <- merge(a,b,by=0)
create_table(data.frame(tukey_df), 'Gender Tukey')
```

```{r, echo=FALSE}
model <- lm(BDI ~ gender * per2, data=aov_data)
tukey <- HSD.test(model, 'per2')
a <- data.frame(tukey$means)
b <- data.frame(tukey$groups)
tukey_df <- merge(a,b,by=0)
create_table(data.frame(tukey_df), 'PER2 Tukey')
```


```{r, echo=FALSE}
model <- lm(BDI ~ age * per2, data=aov_data)
create_table(data.frame(Anova(model, type="III")), 'Age and PER2')
```

```{r, echo=FALSE}
model <- lm(BDI ~ age * per2, data=aov_data)
tukey <- HSD.test(model, 'age')
a <- data.frame(tukey$means)
b <- data.frame(tukey$groups)
tukey_df <- merge(a,b,by=0)
create_table(data.frame(tukey_df), 'AGE Tukey')
```


```{r, results='hide', include = FALSE}

setwd("/Users/tazmilur/Research/mood-disorder-prediction/statistical-analysis/analysis-nocli/STAI1way")
aov_data <- read.csv(file ='baseanova.csv')
options(contrasts = c("contr.helmert", "contr.poly"))

gender <- as.factor(aov_data$GENDER)
age <- as.factor(aov_data$AGE)
socio <- as.factor(aov_data$SOCIO)
per2<- as.factor(aov_data$PER2)
per3a <- as.factor(aov_data$PER3A)
per3b <- as.factor(aov_data$PER3B)
per3c <- as.factor(aov_data$PER3C)
clock <- as.factor(aov_data$CLOCK3111)
cry1 <- as.factor(aov_data$CRY1)
cry2 <- as.factor(aov_data$CRY2)
vntr <- as.factor(aov_data$VNTR)

model <- lm(STAI ~ gender * per2, data=aov_data)
Anova(model, type="III")

model <- lm(STAI ~ gender * per3a, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(STAI ~ gender * per3b, data=aov_data)
Anova(model, type="III")

model <- lm(STAI ~ gender * per3c, data=aov_data)
Anova(model, type="III")

model <- lm(STAI ~ gender * clock, data=aov_data)
Anova(model, type="III")

model <- lm(STAI ~ gender * cry1, data=aov_data)
Anova(model, type="III")

model <- lm(STAI ~ gender * cry2, data=aov_data)
Anova(model, type="III")

model <- lm(STAI ~ gender * vntr, data=aov_data)
Anova(model, type="III")

#----------

model <- lm(STAI ~ socio * per2, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(STAI ~ socio * per3a, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(STAI ~ socio * per3b, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(STAI ~ socio * per3c, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(STAI ~ socio * clock, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(STAI ~ socio * cry1, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(STAI ~ socio * cry2, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

model <- lm(STAI ~ socio * vntr, data=aov_data)
tryCatch(Anova(model, type="III"), error=function(e) NA)

#-----------
# gender and per2
# gender and cry2
```

```{r, echo=FALSE}
model <- lm(STAI ~ gender * per2, data=aov_data)
create_table(data.frame(Anova(model, type="III")), 'Gender and PER2')
```

```{r, echo=FALSE}
model <- lm(STAI ~ gender * per2, data=aov_data)
tukey <- HSD.test(model, 'gender')
a <- data.frame(tukey$means)
b <- data.frame(tukey$groups)
tukey_df <- merge(a,b,by=0)
create_table(data.frame(tukey_df), 'Gender Tukey')
```

```{r, echo=FALSE}
model <- lm(STAI ~ gender * per2, data=aov_data)
tukey <- HSD.test(model, 'per2')
a <- data.frame(tukey$means)
b <- data.frame(tukey$groups)
tukey_df <- merge(a,b,by=0)
create_table(data.frame(tukey_df), 'PER2 Tukey')
```

```{r, echo=FALSE}
model <- lm(STAI ~ per2, data=aov_data)
create_table(data.frame(Anova(model, type="III")), 'PER2')
```

```{r, echo=FALSE}
model <- lm(STAI ~ per2, data=aov_data)
create_table(data.frame(Anova(model, type="III")), 'Gender')
```

```{r, echo=FALSE}
model <- lm(STAI ~ gender * cry2, data=aov_data)
create_table(data.frame(Anova(model, type="III")), 'Gender and CRY2')
```

```{r, echo=FALSE}
model <- lm(STAI ~ gender * cry2, data=aov_data)
tukey <- HSD.test(model, 'cry2')
a <- data.frame(tukey$means)
b <- data.frame(tukey$groups)
tukey_df <- merge(a,b,by=0)
create_table(data.frame(tukey_df), 'CRY2 Tukey')
```

```{r, echo=FALSE}
model <- lm(STAI ~ cry2, data=aov_data)
create_table(data.frame(Anova(model, type="III")), 'CRY2')
```



