--- 
title: "Mood Disorder Project Report"
author: "Tazmilur Saad"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Summary from statistical analysis conducted on the results of the mood disorder project."
---

# Introduction 



## Feature Selection

We used four different feature selection methods: Fast Correlation Based Filter Algorithm (FCBF), Max-Relevance Min-Redundancy (MRMR), Double Input Symmetrical Relevance (DISR), and Joint Mutual Information (JMI). For the multivariate analysis, we ran five fold cross validation and measured how often each feature is selected by all of these methods across each fold. We then accumulated the results and chose the top 10 and top 20 most frequent features. For the top-10 and top-20 features calculated from the 5-way features, we set a limit on the size of the subset of features selected from each fold at 100 for  MRMR, DISR and JMI to reduce the amount of time needed. Besides that, the method used was the same.  

## Accuracy 

Unfortunately, we cannot beat baseline accuracy even with feature selection — which is why we resorted to statistical analysis. With feature selection and proper hypertuning we can reach baseline accuracy, but it’s impossible to beat while maintaining statistical validity.