```{r}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/BDI1way")
```

```{r}
univariate_lr <- function(gender, disease) {
  ratio_oneway_BDI <- data.frame(log_odds=numeric(), conf25=numeric(), conf75=numeric(), p_z=numeric(), name=character())
  f_path = paste('split/',gender,sep='')
  files <- list.files(path=f_path, pattern="*.csv", full.names=TRUE, recursive=FALSE)

  for (f in files) {
    data <- read.csv(file =f)
    res = glm(STAI ~ .,data=data,family=binomial())
    trm <- attr(res$terms, "term.labels")
    for (i in (seq(2,dim(data)[2],by=1))) {
      a <- c(exp(summary(res)$coef[i,][1]), confint(res)[i,], summary(res)$coef[i,][4], trm[i-1])
      ratio_oneway_BDI[nrow(ratio_oneway_BDI) + 1,] = a
    }
  }
  adjusted <- p.adjust(ratio_oneway_BDI[, c('p_z')], method="BH")
  ratio_oneway_BDI$adjusted_p = adjusted

  f_name = paste('Univariate_',disease,'_',gender,'.csv',sep='')
  write.csv(ratio_oneway_BDI, f_name)
}
```

```{r}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/BIC/BDI2way")
bicglm('gendered', 'BDI')
bicglm('male', 'BDI')
bicglm('female', 'BDI')
```


```{r}
multivariate_lr <- function(gender, disease) {
  
  f_path <- paste('combined/',gender,'/combined.csv',sep='')
  data2 <- read.csv(file =f_path)
  multi = glm(STAI ~ ., data=data2, family=binomial())
  placeholder = data.frame(multi_log_odds=numeric(), multi_conf25=numeric(), multi_conf75=numeric(), multi_p_z=numeric(), name=character())

  for (i in seq(2, (length(summary(multi)$coef)/4), by=1)){
    trm <- attr(multi$terms, "term.labels")
    if (is.na(multi$coefficients[i])) {
      b <- c(NA, NA, NA, NA, trm[i-1])
      placeholder[nrow(placeholder) + 1,] = b
    } else {
      a <- tryCatch(confint(multi, trm[i-1]), error=function(e) c(NA,NA))
      b <- c(exp(summary(multi)$coef[i,][1]), a, summary(multi)$coef[i,][4], trm[i-1])
      #b <- c(exp(multi$coefficients[i]), a, coef(summary(multi))[i,][4], trm[i-1])
      placeholder[nrow(placeholder) + 1,] = b
    }
  }

  adjusted2 <- p.adjust(placeholder[, c('multi_p_z')], method="BH")
  placeholder$multi_adjusted_p = adjusted2
  
  f_name = paste('Multivaraite_',disease,'_',gender,'.csv',sep='')
  write.csv(placeholder, f_name)
}
```

```{r}
fisherexact <- function(gender, disease) {
  
  f_path <- paste('combined/',gender,'/combined.csv',sep='')
  data2 <- read.csv(file =f_path)
  
  placeholder2 = data.frame(fisher_p_z=numeric())

  for (i in 1:(dim(data2)[2]-1)){
    c <- crosstab(data2[,ncol(data2)], data2[,i], fisher=TRUE)
    placeholder2[nrow(placeholder2) + 1,] = c$fisher.ts$p.value
  }

  adjusted3 <- p.adjust(placeholder2[, c('fisher_p_z')], method="BH")
  placeholder2$fisher_adjusted_p = adjusted3
  placeholder2$names = colnames(data2)[1:(dim(data2)[2]-1)]

  f_name = paste('Fisher_',disease,'_',gender,'.csv',sep='')
  write.csv(placeholder2, f_name)
}
```

```{r}
bicglm <- function(gender, disease) {
  f_path <- paste('combined/',gender,'/combined.csv',sep='')
  data <- read.csv(file =f_path)
  fit <- bestglm(data, family=gaussian, IC='BIC', method='forward',nvmax=50)
  filename = paste(gender,disease,'BIC_best_glm.csv',sep="_")
  res<-lm(y ~ ., data=fit$BestModel$model)
  df <- data.frame(coef(res))
  df <- cbind(df, confint(res))
  df <- cbind(df, summary(res)$coefficients[,4])
  df$r_squared <- summary(res)$r.squared
  df$adj_r_squared <- summary(res)$adj.r.squared
  write.csv(df, filename)
}
```

```{r}

```


```{r}
anova <- function(gender,  disease) {
  f_path <- paste('combined/',gender,'/combined.csv',sep='')
  data <- read.csv(file =f_path)

  anova <- aov(MEQ ~ ., data=data)
  tukey.test <- TukeyHSD(anova)
  out <- capture.output(summary(anova))
  filename = paste(gender,disease,'anova_split',sep="_")
  cat(paste("Anova of",disease,'and',gender,'from file',fsep=" "),out,file=filename, sep='\n', append=TRUE)
}
```

```{r}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/BIC/BDI1way/combined/gendered/")
data <- read.csv('combined.csv')
fit <- bestglm(data, family=gaussian,IC='BIC', method='forward',nvmax=50)
```
```{r}
res<-lm(y ~ ., data=fit$BestModel$model)
df <- data.frame(coef(res))
df <- cbind(df, confint(res))
df <- cbind(df, summary(res)$coefficients[,4])
df 
```


```{r}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/STAI1way")
aov_data <- read.csv(file ='baseanova.csv')
options(contrasts = c("contr.helmert", "contr.poly"))

gender <- as.factor(aov_data$GENDER)
age <- as.factor(aov_data$AGE)
socio <- as.factor(aov_data$SOCIO)
per2<- as.factor(aov_data$PER2)
per3a <- as.factor(aov_data$PER3A)
per3b <- as.factor(aov_data$PER3B)
per3c <- as.factor(aov_data$PER3C)
clock <- as.factor(aov_data$CLOCK3111)
cry1 <- as.factor(aov_data$CRY1)
cry2 <- as.factor(aov_data$CRY2)
vntr <- as.factor(aov_data$VNTR)
```

```{r}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/STAI1way/anovaresults/")
var = 'cry2'
kruskal <- kruskal.test(STAI ~ cry2, data=aov_data)
df <- data.frame(kruskal$data.name, kruskal$statistic, kruskal$p.value)
PT <- dunnTest(STAI ~ cry2, data=aov_data, method='bh')
df_pt <- data.frame(PT$res)
write.csv(df, paste('kruskal_',var,'.csv',sep=''))
write.csv(df_pt, paste('dunntest_',var,'.csv',sep=''))
```


```{r}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/MEQ2way/combined/gendered/")
data <- read.csv('combined.csv')
x_vars <- model.matrix(MEQ ~. , data)[,-1]
y_var <- data$MEQ

set.seed(86)
train = sample(1:nrow(x_vars), nrow(x_vars)/2)
lambda_seq <- 10^seq(2, -2, by = -.1)
x_test = (-train)
y_test = y_var[x_test]

cv_output <- cv.glmnet(x_vars[train,], y_var[train],
                       alpha = 1, lambda = lambda_seq, 
                       nfolds = 5)

best_lam <- cv_output$lambda.min
lasso_best <- glmnet(x_vars[train,], y_var[train], alpha = 1, lambda = best_lam)
df <- data.frame(as.matrix(coef(lasso_best)))
write.csv(df, 'lasso.csv')
```

```{r}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/STAI5way/top/")
top_data <- read.csv('20feature_dataset.csv')
#top_data <- subset(top_data, select = -c(X))

df <- data.frame(odds_ratio=numeric(), conf25=numeric(), conf75=numeric(), p_z=numeric(), name=character())
for (i in 1:dim(top_data)[2]) {
  res = glm(STAI ~ .,data=subset(top_data, select=c(i, ncol(top_data))),family=binomial())
  a <- c(exp(summary(res)$coef[2,][1]), confint(res)[2,], summary(res)$coef[2,][4], colnames(top_data)[i])
  df[nrow(df) + 1,] = a
}
adjusted <- p.adjust(df[, c('p_z')], method="BH")
df$adjusted_p = adjusted

setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/")
write.csv(df, 'top20STAI_univariate.csv')
```

```{r}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/MEQ2way/top/gendered/")
top_data <- read.csv('20feature_dataset.csv')
#top_data <- subset(top_data, select = -c(X))

multi = glm(MEQ ~ ., data=top_data, family=binomial())
df = data.frame(odds_ratio=numeric(), multi_conf25=numeric(), multi_conf75=numeric(), multi_p_z=numeric(), name=character())

for (i in seq(2, (length(summary(multi)$coef)/4), by=1)){
  trm <- attr(multi$terms, "term.labels")
  if (is.na(multi$coefficients[i])) {
    b <- c(NA, NA, NA, NA, trm[i-1])
    df[nrow(df) + 1,] = b
  } else {
    a <- tryCatch(confint(multi, trm[i-1]), error=function(e) c(NA,NA))
    b <- c(exp(summary(multi)$coef[i,][1]), a, summary(multi)$coef[i,][4], trm[i-1])
    df[nrow(df) + 1,] = b
    }
}

adjusted <- p.adjust(df[, c('multi_p_z')], method="BH")
df$multi_adjusted_p = adjusted

write.csv(df, 'top20_multivariate.csv')
```


```{r}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/STAI5way/top/")
top_data <- read.csv('20feature_dataset.csv')
#top_data <- subset(top_data, select = -c(X))
  
df = data.frame(fisher_p_z=numeric())

for (i in 1:(dim(top_data)[2]-1)){
  c <- crosstab(top_data[,ncol(top_data)], top_data[,i], fisher=TRUE)
  df[nrow(df) + 1,] = c$fisher.ts$p.value
}

adjusted3 <- p.adjust(df[, c('fisher_p_z')], method="BH")
df$fisher_adjusted_p = adjusted3
df$names = colnames(top_data)[1:(dim(top_data)[2]-1)]

setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/")
write.csv(df, 'top20STAI_fisher.csv')
```



```{r}
setwd("/Users/tazmilur/Research/mood-disorder-prediction/analysis/BDI1way/anovaresults/")
var = 'per3a'
crf.lm <-lm(BDI ~ gender * per3a, data=aov_data)

res_aov <- Anova(crf.lm, type=3)
#tukey <- HSD.test(crf.lm, var, console=TRUE)
#a <- data.frame(tukey$means)
#b <- data.frame(tukey$groups)
#tukey_df <- merge(a,b,by=0)
aov_df <- data.frame(res_aov)

write.csv(aov_df, paste('anova_interaction_gender_',var,'.csv',sep=''))
#write.csv(tukey_df, paste('tukey_',var,'.csv',sep=''))
```

```{r}
l <- lm(MEQ ~ gender * per2, data=aov_data)
av <- Anova(l, type=3)
tkey <- HSD.test(l, 'per2', console=TRUE)
```


